### ISSUE TITLE
Add lighthouse audit scores to detailed display of system status

### ISSUE THREAD

**Issue by jwalter1107** [USSBA/sba-status#14]
_Description:_
As a CIO, I want to publicly show the score of my various properties to the public, as a part of my system status, so that I can shed a lot of sunlight and disinfect my agency from bad technology.

_Assumptions:_
- TBD

_Acceptance Criteria:_
- Current (last measured) lighthouse audit score displays under ‘details’ as part of the status.sba.gov page, for each system
- Last measured date also displays for the system

**Comment by bushong1** [comment]
Added with static page
